version: "3.8"

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
    env_file:
      - .env
  redis:
    build: requirements/redis/
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      inception:
networks:
  inception:
    driver: bridge