version: "3.8"

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
    env_file:
      - .env
  redis:
    build: requirements/redis/
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      inception:

  ftp:
    depends_on:
      - wordpress
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    networks:
      inception:
    env_file:
      - .env
    volumes:
    - ./web:/var/www/html
  adminer:
    container_name: adminer
    build: ./requirements/adminer/
    restart: always
    depends_on:
      - mariadb
    networks:
      inception:
    ports:
      - "8080:8080"

networks:
  inception:
    driver: bridge
