FROM debian:latest

ENV PORTAINER_VERSION=2.14.2 \
    PORTAINER_HOME=/var/lib/portainer

RUN apt update && \
    apt upgrade -y && \
    apt install -y bash curl dnsutils ca-certificates jq tar    && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://github.com/portainer/portainer/releases/download/${PORTAINER_VERSION}/portainer-${PORTAINER_VERSION}-linux-amd64.tar.gz | \
    tar -xz -C /usr/local

WORKDIR /usr/local/portainer


CMD ["/usr/local/portainer/portainer"]

