FROM debian:latest

RUN apt update && \
    apt upgrade -y && \
    apt install -y bash curl dnsutils ca-certificates jq tar    && \
    rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://github.com/portainer/portainer/releases/download/2.14.2/portainer-2.14.2-linux-amd64.tar.gz | \
    tar -xz -C /usr/local

WORKDIR /usr/local/portainer

CMD ["/usr/local/portainer/portainer"]

