FROM debian:latest


RUN apt update && \
    apt upgrade -y && apt install -y nginx openssl \
    && rm -rf /var/lib/apt/lists/*


RUN mkdir -p /etc/ssl

RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
     -out /etc/ssl/namoussa.42.fr.pem \
     -keyout /etc/ssl/namoussa.42.fr.key \
     -subj "/C=FR/ST=BEN GUERIR/L=BEN GUERIR/O=1337 School/OU=namoussa/CN=namoussa.42.fr"

COPY ./conf/default /etc/nginx/sites-available/

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
