FROM alpine:3.12.0

RUN apk update ; \
	apk add php7-common php7-iconv php7-json php7-curl \
	php7-mysqli  php7-cgi fcgi php7-pdo php7-pdo_mysql php7 php7-fpm php7-opcache php7-session; \
	rm -rf /var/cache/apk/*

RUN wget "https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php"

RUN mv adminer-4.8.1.php index.php

CMD ["php", "-S", "0.0.0.0:8080"]


