FROM debian:buster

# Install necessary packages
RUN apt-get update && apt-get install -y wget php

# Ensure the target directory exists
RUN mkdir -p /var/www/html

# Copy the script into the container
COPY ./tools/adminer.sh /tmp/adminer.sh

# Ensure the script is executable
RUN chmod +x /tmp/adminer.sh

# Run the script on container startup
ENTRYPOINT [ "sh", "/tmp/adminer.sh" ]
