FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    bash \
    php8.2 \
    php8.2-fpm \
    php8.2-mysql \
    php8.2-pdo \
    php8.2-gd \
    php8.2-cli \
    php8.2-mbstring \
    redis \
    php8.2-redis \
    && rm -rf /var/lib/apt/lists/*

# Install WP-CLI
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp

# Copy the PHP configuration
COPY ./conf/www.conf /etc/php/8.2/fpm/pool.d/

# Create PHP run directory
RUN mkdir -p /run/php

# Set working directory
WORKDIR /var/www/html/

# Expose PHP-FPM port
EXPOSE 9000

# Copy WordPress installation script
COPY ./tools/create_wordpress.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/create_wordpress.sh

ENTRYPOINT ["/usr/local/bin/create_wordpress.sh"]


