FROM debian:bookworm

RUN apt-get -y update && apt-get install -y \
    wget \
    curl \
    bash \
    php8.2 \
    php8.2-fpm \
    php8.2-mysql \
    php8.2-pdo \
    php8.2-gd \
    php8.2-cli \
    php8.2-mbstring \
    redis \
    php8.2-redis \
    && rm -rf /var/lib/apt/lists/*


RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp


COPY ./conf/www.conf /etc/php/8.2/fpm/pool.d/


RUN mkdir -p /run/php


WORKDIR /var/www/html/


EXPOSE 9000


COPY ./tools/create_wordpress.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/create_wordpress.sh

ENTRYPOINT ["/usr/local/bin/create_wordpress.sh"]


